### ISSUE TITLE
Substituir "const preload = function ()"

### ISSUE THREAD

**Issue by bschorchit** [JsLadiesBR/tutorial#24]
// funcao de carregar as imagens e outros recursos
function preload () {
    // Carrega os recursos de imagens para o jogo
    this.load.atlas('hamtaro_atlas', 'assets/sprites/hamtaro/hamham.png', 'assets/sprites/maps/hamtaro.json')
    this.load.atlas('comida_atlas', 'assets/sprites/assest/food.png', 'assets/sprites/maps/food.json')
}

**Comment by narukaioh** [comment]
Alterada a função
